# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_thread_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nickname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.IntegerField(default=1)),
                ('thread_no', models.IntegerField(default=1)),
                ('nickname', models.CharField(max_length=100)),
            ],
        ),
    ]
