# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='nickname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='nickname',
            name='nickname',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='nickname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
