# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 20:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170318_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nickname',
            old_name='author_id',
            new_name='aid',
        ),
        migrations.RenameField(
            model_name='nickname',
            old_name='nickname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='nickname',
            old_name='thread_no',
            new_name='tno',
        ),
    ]
