# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170319_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nickname',
            old_name='aid',
            new_name='nid',
        ),
        migrations.RemoveField(
            model_name='nickname',
            name='tno',
        ),
    ]
