# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170322_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='within_post_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='comment_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
