# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='num_recommendation',
            field=models.IntegerField(default=0),
        ),
    ]
