# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 06:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_num_recommendation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='post',
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
