# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20170329_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='num_read',
            field=models.IntegerField(default=0),
        ),
    ]
