# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 02:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_num_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='blog.Post')),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='approved_comment',
        ),
    ]
