# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_comment_approved_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='report_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
