# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_post_report_cnt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='report_cnt',
            new_name='num_user_comment',
        ),
        migrations.AddField(
            model_name='post',
            name='num_user_report',
            field=models.IntegerField(default=0),
        ),
    ]
